#!/usr/bin/env python3
"""Fold config/overrides.toml into ps1Analyzer's generated config.

Usage: merge_overrides.py <analyzer.toml> <overrides.toml> <out.toml> --exe <path> --cue <path>

Override [[hle_functions]] entries replace any analyzer entry at the same
address.  They default to hle = true, so ps1Recomp routes them to the
runtime's native implementation; hle = false instead forces a misidentified
function back to plain recompilation.  A [disc] section pointing at the user's own files is
written last.  The output is plain generated data: regenerate it, don't edit it.
"""
import argparse
import re
import tomllib


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("analyzer")
    ap.add_argument("overrides")
    ap.add_argument("out")
    ap.add_argument("--exe", required=True)
    ap.add_argument("--cue", required=True)
    ap.add_argument("--release", help="also write the small game.toml a packaged "
                    "build ships beside the executable (no paths, no disc data)")
    a = ap.parse_args()

    text = open(a.analyzer, encoding="utf-8-sig").read()
    overrides = tomllib.load(open(a.overrides, "rb"))
    ov = overrides.get("hle_functions", [])
    regions = overrides.get("regions", [])

    # Drop analyzer blocks of one array-of-tables kind whose address is in
    # `addrs`.  Blocks run from their header to the next blank line.
    def drop(text, table, addrs):
        parts = re.split(r"(?m)^(?=\[\[%s\]\]\n)" % table, text)
        out, n = [parts[0]], 0
        for p in parts[1:]:
            head, _, rest = p.partition("\n\n")
            m = re.search(r'^address = "(0x[0-9A-Fa-f]+)"', head, re.M)
            if m and int(m.group(1), 16) in addrs:
                n += 1
                out.append(rest)
            else:
                out.append(p)
        return "".join(out), n

    overridden = {int(h["address"], 16) for h in ov}
    text, dropped = drop(text, "hle_functions", overridden)
    # The analyzer also lists some matches under legacy [[stubs]], which
    # ps1Recomp binds by name after [[functions]] -- left in, a stub would
    # still win the call sites of an address an override took over.
    text, _ = drop(text, "stubs", overridden)
    text = re.sub(r"(?ms)^\[disc\]\n.*?(?=^\[|\Z)", "", text)

    # [[regions]]: hand-written code whose fragments jump into one another.
    # Each listed fragment start, plus each extra entry (continuations, call
    # targets), becomes a copy of the whole region that starts at that entry,
    # so every transfer inside it is a local goto.
    region_funcs = []
    for r in regions:
        lo, hi = int(r["start"], 16), int(r["end"], 16)
        members = {int(x, 16) for x in r["replace"]}
        text, _ = drop(text, "functions", members)
        for e in sorted(members | {int(x, 16) for x in r.get("entries", [])}):
            if not lo <= e < hi:
                raise SystemExit("region entry 0x%08X outside region" % e)
            region_funcs += ["[[functions]]",
                             'name = "func_%08X"' % e,
                             'address = "0x%08X"' % lo,
                             "size = %d" % (hi - lo),
                             'entry = "0x%08X"' % e,
                             'source = "region"',
                             "leaf = false",
                             ""]

    # An address the analyzer only knew as a PsyQ match has no [[functions]]
    # entry.  Un-HLE'ing it without adding one makes ps1Recomp emit an EMPTY
    # body ("STUB generated by JAL") -- the function silently does nothing.
    # Give it a real entry, sized up to the next known function start.
    base = tomllib.loads(text)
    known = {int(f["address"], 16) for f in base.get("functions", [])}
    starts = sorted(known | {int(h["address"], 16)
                             for h in base.get("hle_functions", [])})
    extra = []
    for h in ov:
        addr = int(h["address"], 16)
        if h.get("hle", True) or addr in known:
            continue
        nxt = next((s for s in starts if s > addr), None)
        if nxt is None:
            raise SystemExit("cannot size %s: no following function" % h["address"])
        extra += ["[[functions]]",
                  'name = "func_%08X"' % addr,
                  'address = "0x%08X"' % addr,
                  "size = %d" % (nxt - addr),
                  'source = "override"',
                  "leaf = false",
                  ""]

    lines = [text.rstrip("\n"), ""] + extra + region_funcs
    for h in ov:
        lines += ["[[hle_functions]]",
                  'name = "%s"' % h["name"],
                  'address = "%s"' % h["address"],
                  "hle = %s" % ("true" if h.get("hle", True) else "false"),
                  'stub_type = "override"',
                  ""]
    for p in overrides.get("patches", []):
        lines += ["[[patches]]",
                  'address = "%s"' % p["address"],
                  'value = "%s"' % p["value"]]
        if "expect" in p:
            lines.append('expect = "%s"' % p["expect"])
        lines.append("")
    # [[cheats]]: named groups of RAM pokes the runtime's overlay menu offers.
    for c in overrides.get("cheats", []):
        lines += ["[[cheats]]",
                  'name = "%s"' % c["name"],
                  "pokes = [%s]" % ", ".join('"%s"' % p for p in c["pokes"]),
                  ""]
    # [runtime]: presentation settings for the runtime (window title).
    rt = overrides.get("runtime", {})
    if rt:
        lines.append("[runtime]")
        lines += ['%s = "%s"' % (k, v) for k, v in rt.items()]
        lines.append("")
    lines += ["[disc]",
              'exe_path = "%s"' % a.exe.replace("\\", "/"),
              'cue_path = "%s"' % a.cue.replace("\\", "/"),
              ""]
    open(a.out, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
    tomllib.load(open(a.out, "rb"))  # fail loudly on a malformed result
    if a.release:
        rel = ["# Shipped beside the executable.  The disc image is chosen by the",
               "# player on first run (settings.ini); nothing here comes from the disc.",
               ""]
        if rt:
            rel.append("[runtime]")
            rel += ['%s = "%s"' % (k, v) for k, v in rt.items()]
            rel.append("")
        boot = overrides.get("disc", {}).get("boot")
        if boot:
            rel += ["[disc]", 'boot = "%s"' % boot, ""]
        for c in overrides.get("cheats", []):
            rel += ["[[cheats]]",
                    'name = "%s"' % c["name"],
                    "pokes = [%s]" % ", ".join('"%s"' % p for p in c["pokes"]),
                    ""]
        open(a.release, "w", encoding="utf-8", newline="\n").write("\n".join(rel))
        tomllib.load(open(a.release, "rb"))
    print("merged %d override(s), replaced %d analyzer entr%s, %d region "
          "entr%s -> %s"
          % (len(ov), dropped, "y" if dropped == 1 else "ies",
             len(region_funcs) // 8, "y" if len(region_funcs) == 8 else "ies",
             a.out))


if __name__ == "__main__":
    main()
